Modified codemagic.yaml to get APK build.  Client price offset takes negatives.

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -54,6 +54,12 @@ workflows:
           ./gradlew assembleRelease \
             -PversionCode=$(($BUILD_NUMBER + 1104))  \
             -PversionName=1.$(($BUILD_NUMBER + 104))
+          if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
+            echo "APK generated successfully."
+          else
+            echo "APK generation failed."
+            exit 1
+          fi
       - name: Export AAB
         script: |
           cd dist/android
